name: emoji_logger
description: >-
  Simple logger that uses emoji to
  highlight log print lines with ease
version: 0.0.1
homepage: https://github.com/mohmdezeldeen/emoji_logger.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: